// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkiQWw9Pegmk_KQEjbJR_cMrKkX3f-cwA',
    appId: '1:135181959438:web:f3d918112c71dcba1e975f',
    messagingSenderId: '135181959438',
    projectId: 'os-3-2444b',
    authDomain: 'os-3-2444b.firebaseapp.com',
    storageBucket: 'os-3-2444b.firebasestorage.app',
    measurementId: 'G-PRF27K04GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKne0jKgpoTrGxMF6bb-zJBp7SMMrMhKg',
    appId: '1:135181959438:android:ddfa42d0c6080a181e975f',
    messagingSenderId: '135181959438',
    projectId: 'os-3-2444b',
    storageBucket: 'os-3-2444b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuWqoQHPBm1qP3hcdGFNERZrsUn-Qds1M',
    appId: '1:135181959438:ios:a2422933840b40c01e975f',
    messagingSenderId: '135181959438',
    projectId: 'os-3-2444b',
    storageBucket: 'os-3-2444b.firebasestorage.app',
    iosBundleId: 'com.example.os3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuWqoQHPBm1qP3hcdGFNERZrsUn-Qds1M',
    appId: '1:135181959438:ios:a2422933840b40c01e975f',
    messagingSenderId: '135181959438',
    projectId: 'os-3-2444b',
    storageBucket: 'os-3-2444b.firebasestorage.app',
    iosBundleId: 'com.example.os3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkiQWw9Pegmk_KQEjbJR_cMrKkX3f-cwA',
    appId: '1:135181959438:web:e9a2656f260a57491e975f',
    messagingSenderId: '135181959438',
    projectId: 'os-3-2444b',
    authDomain: 'os-3-2444b.firebaseapp.com',
    storageBucket: 'os-3-2444b.firebasestorage.app',
    measurementId: 'G-DHB5TY3QSM',
  );
}
